### ISSUE TITLE
No sound on primary/secondary fire, visual problem

### ISSUE THREAD

**Issue by TheRealToner** [CapsAdmin/wowozela#20]
This is no longer working for me. I suspect this is due to some sort of mod conflict, but I have yet to determine which one(s).

When I attempt to use it (left or right click) no sound is played. There is a single particle effect that appears when holding down either use button, but its only the one and does not remain. When choosing a sound on the wheel, the sound _does_ play but only when clicked on and the pitch cannot be changed.

I will try to narrow down which mod it is conflicting with, if it is at all.

Despite this, I would still like to applaud you on this mod, I think its real neat!

**Comment by Xerasin** [comment]
Likely replication of #16, please provide more clarification if this is not the case.
